export const SELECT_PX_ENGAGEMENT = 'Select PX Engagement'
export const ACTIVE_ENGAGEMENTS = 'Active Engagements'
export const SEARCH_BY_NAME = 'Search By Name'
export const SELECT_ALL = 'Select All'
export const SELECTED = 'Selected'
export const ALL = 'All'
export const SORT_BY = 'Sort by'
